### ISSUE TITLE
Problems with external links on index. html

### ISSUE THREAD

**Issue by AlessandroGuarnuto** [Autodesk-Forge/forge-bim360reports#26]
Hi...
I have a question..
Why did I have problems with external links after I developed my app on Heroku?

When I start my app locally it works.
After I developed it on heroku, my href = External links specified on the index. html file change and when I click on them from the browser it updates the page.

Thanks

**Comment by jaimerosales** [comment]
You might want to remove from index.html this part
https://github.com/Autodesk-Forge/bim360appstore-viewer-nodejs-visual.reports/blob/master/www/index.html#L119

**Comment by jaimerosales** [comment]
No response.
