### ISSUE TITLE
Big Projects dont show any information

### ISSUE THREAD

**Issue by wrartes** [Autodesk-Forge/forge-bim360reports#9]
I tried the tool I some projects and works great on small projects, big projects don't show any information at all.

**Comment by jaimerosales** [comment]
If it is a big project, the events that create the report wait until all the geometry of the model gets loaded. I will say try to wait or just relaunch the same project to see if that triggers the full loading of the model.

**Comment by jaimerosales** [comment]
No response, reopen if needed.
